-- CreateEnum
CREATE TYPE "MotivoVisita" AS ENUM ('COMPRA_CLIENTE', 'PRESENTACION_PRODUCTOS', 'NEGOCIACION_PRECIOS', 'ENTREGA_MUESTRAS', 'PLANIFICACION_PEDIDOS', 'CONSULTA_CLIENTE', 'SEGUIMIENTO', 'PROMOCION', 'OTRO');

-- CreateEnum
CREATE TYPE "TipoVisita" AS ENUM ('PRESENCIAL', 'VIRTUAL');

-- AlterTable
ALTER TABLE "Visita" ADD COLUMN     "motivoVisita" "MotivoVisita",
ADD COLUMN     "tipoVisita" "TipoVisita";
